<?php
/**
 * Spreadsheet Generator Functions
 */

// Note: In a production environment, you would use libraries like:
// - PhpSpreadsheet (for Excel)
// - TCPDF or Dompdf (for PDF)
// - Or use a service

// This is a simplified version for demonstration

function generate_excel_file($products, $totals) {
    // This would use PhpSpreadsheet in production
    // For now, we'll create a simple CSV
    
    $csv_content = generate_csv_content($products, $totals);
    
    // Create temporary file
    $upload_dir = wp_upload_dir();
    $filename = 'revenue-report-' . date('Y-m-d-H-i-s') . '.xlsx';
    $filepath = $upload_dir['path'] . '/' . $filename;
    
    // In production, you would generate actual Excel file
    // For demo, we'll create a CSV with .xlsx extension
    file_put_contents($filepath, $csv_content);
    
    return $upload_dir['url'] . '/' . $filename;
}

function generate_pdf_report($products, $totals) {
    // This would use TCPDF or Dompdf in production
    // For now, we'll create an HTML file
    
    $html = '<!DOCTYPE html>
    <html>
    <head>
        <title>Revenue Report</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            h1 { color: #333; border-bottom: 2px solid #667eea; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin: 20px 0; }
            th { background: #f7fafc; padding: 12px; text-align: left; border-bottom: 2px solid #e2e8f0; }
            td { padding: 10px; border-bottom: 1px solid #e2e8f0; }
            .summary { background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }
            .profit-positive { color: #48bb78; }
            .profit-negative { color: #f56565; }
        </style>
    </head>
    <body>
        <h1>Revenue Calculator Report</h1>
        <p>Generated: ' . date('Y-m-d H:i:s') . '</p>
        
        <h2>Product Details</h2>
        <table>
            <tr>
                <th>Item Name</th>
                <th>Cost ($)</th>
                <th>Price ($)</th>
                <th>Quantity</th>
                <th>Total Cost</th>
                <th>Total Revenue</th>
                <th>Profit</th>
                <th>Margin</th>
            </tr>';
    
    foreach ($products as $product) {
        $margin = $product['price'] > 0 ? (($product['price'] - $product['cost']) / $product['price'] * 100) : 0;
        $profit_class = $product['profit'] >= 0 ? 'profit-positive' : 'profit-negative';
        
        $html .= '<tr>
            <td>' . htmlspecialchars($product['name']) . '</td>
            <td>$' . number_format($product['cost'], 2) . '</td>
            <td>$' . number_format($product['price'], 2) . '</td>
            <td>' . $product['quantity'] . '</td>
            <td>$' . number_format($product['totalCost'], 2) . '</td>
            <td>$' . number_format($product['totalRevenue'], 2) . '</td>
            <td class="' . $profit_class . '">$' . number_format($product['profit'], 2) . '</td>
            <td>' . number_format($margin, 2) . '%</td>
        </tr>';
    }
    
    $html .= '</table>
        
        <div class="summary">
            <h2>Summary</h2>
            <p><strong>Total Cost:</strong> $' . number_format($totals['totalCost'], 2) . '</p>
            <p><strong>Total Revenue:</strong> $' . number_format($totals['totalRevenue'], 2) . '</p>
            <p><strong>Total Profit:</strong> $' . number_format($totals['totalProfit'], 2) . '</p>';
    
    $profit_margin = $totals['totalRevenue'] > 0 ? ($totals['totalProfit'] / $totals['totalRevenue'] * 100) : 0;
    $html .= '<p><strong>Profit Margin:</strong> ' . number_format($profit_margin, 2) . '%</p>
        </div>
        
        <div class="footer">
            <p>This report was generated by Revenue Calculator WordPress Theme</p>
        </div>
    </body>
    </html>';
    
    // Create temporary file
    $upload_dir = wp_upload_dir();
    $filename = 'revenue-report-' . date('Y-m-d-H-i-s') . '.pdf';
    $filepath = $upload_dir['path'] . '/' . $filename;
    
    // In production, convert HTML to PDF
    // For demo, we'll save as HTML
    file_put_contents($filepath, $html);
    
    return $upload_dir['url'] . '/' . $filename;
}